# Generated by Django 4.2.7 on 2025-12-03 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_company_encryption_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('_revenue', models.TextField(db_column='revenue', help_text='Encrypted revenue amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date'], name='sales_recor_company_fb4f4a_idx')],
            },
        ),
    ]
