# Generated by Django 4.2.7 on 2025-12-03 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_email_verified_user_verification_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_code', models.CharField(db_index=True, max_length=100)),
                ('collection_name', models.CharField(blank=True, max_length=100)),
                ('collection_group', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection Master',
            },
        ),
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gold Rate',
                'verbose_name_plural': 'Gold Rates',
            },
        ),
        migrations.AlterModelOptions(
            name='salesrecord',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.RemoveIndex(
            model_name='salesrecord',
            name='sales_recor_company_fb4f4a_idx',
        ),
        migrations.RenameField(
            model_name='salesrecord',
            old_name='date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='_revenue',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='base_metal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='client_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='collection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='color_stone_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='color_stone_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='entry_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='free_gold_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='jewel_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='product_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='product_subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='solitaire_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='solitaire_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='store_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='style_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_diamond_pieces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_diamond_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['company', 'transaction_date'], name='analytics_s_company_0ca8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['company', 'style_code'], name='analytics_s_company_7099f9_idx'),
        ),
        migrations.AlterModelTable(
            name='salesrecord',
            table=None,
        ),
        migrations.AddField(
            model_name='goldrate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_rates', to='core.company'),
        ),
        migrations.AddField(
            model_name='goldrate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionmaster',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.company'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionmaster',
            unique_together={('company', 'style_code')},
        ),
    ]
