# Generated by Django 4.2.7 on 2025-12-06 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_user_users_email_4b85f2_idx'),
        ('analytics', '0002_collectionmaster_goldrate_alter_salesrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('sales', 'Sales Data'), ('stock', 'Stock Data'), ('crm', 'CRM Data')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('rows_ignored', models.IntegerField(default=0)),
                ('columns_mapped', models.JSONField(default=list)),
                ('columns_unmapped', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Import Log',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewel_code', models.CharField(max_length=100)),
                ('style_code', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('base_metal', models.CharField(blank=True, max_length=50)),
                ('item_size', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pure_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('diamond_pieces', models.IntegerField(default=0)),
                ('diamond_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('color_stone_pieces', models.IntegerField(default=0)),
                ('color_stone_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date', 'style_code'],
            },
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gross_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='sales_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('ignored', 'Ignored')], default='sale', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['company', 'transaction_type'], name='analytics_s_company_0bd764_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['company', 'region'], name='analytics_s_company_342650_idx'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='core.company'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='core.company'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['company', 'style_code'], name='analytics_s_company_7221cc_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['company', 'location'], name='analytics_s_company_aa57d3_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['company', 'category'], name='analytics_s_company_9aea1b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['company', 'snapshot_date'], name='analytics_s_company_de2596_idx'),
        ),
    ]
