# Generated by Django 4.2.7 on 2025-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_importlog_stocksnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksnapshot',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='stock_month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='stock_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
