# Generated by Django 4.2.7 on 2025-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_stocksnapshot_certificate_no_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['company', 'transaction_date', '-final_amount'], name='analytics_s_company_cdec98_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['company', 'sales_person', 'transaction_date'], name='analytics_s_company_b51f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['transaction_date', 'transaction_type'], name='analytics_s_transac_33ee4d_idx'),
        ),
    ]
