# Generated by Django 4.2.7 on 2025-12-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_modules'),
        ('analytics', '0005_salesrecord_analytics_s_company_cdec98_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('lead_source', models.CharField(blank=True, max_length=100)),
                ('lead_status', models.CharField(blank=True, max_length=50)),
                ('original_lead_source', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('interest_category', models.CharField(blank=True, max_length=255)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('loyalty_redeemed', models.IntegerField(default=0)),
                ('loyalty_earned', models.IntegerField(default=0)),
                ('last_engagement_date', models.DateField(blank=True, null=True)),
                ('total_signal_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_person', models.CharField(blank=True, max_length=100)),
                ('original_sales_person', models.CharField(blank=True, max_length=100)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='core.company')),
            ],
            options={
                'verbose_name': 'CRM Contact',
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['company', 'mobile'], name='analytics_c_company_e2a456_idx'), models.Index(fields=['company', 'store_name'], name='analytics_c_company_2e6c85_idx'), models.Index(fields=['company', 'lead_status'], name='analytics_c_company_4847fc_idx'), models.Index(fields=['company', 'dob'], name='analytics_c_company_595fce_idx')],
            },
        ),
    ]
