# Generated by Django 4.2.7 on 2025-12-07 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_users_email_4b85f2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Unique identifier e.g., 'expenses', 'btl'", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='box', help_text='Lucide icon name', max_length=50)),
                ('url_name', models.CharField(help_text="Django URL name e.g., 'expenses:list'", max_length=100)),
                ('color_class', models.CharField(default='primary', help_text='Bootstrap color class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on dashboard')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.CreateModel(
            name='BackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to backup file when completed', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_tasks', to='core.company')),
                ('module', models.ForeignKey(blank=True, help_text='Null means all modules', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_tasks', to='core.module')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_module_allocations', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allocations', to='core.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_modules',
                'ordering': ['module__order'],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_module_allocations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_modules', to='core.company')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_allocations', to='core.module')),
            ],
            options={
                'db_table': 'company_modules',
                'ordering': ['module__order'],
                'unique_together': {('company', 'module')},
            },
        ),
    ]
