# Generated by Django 4.2.7 on 2025-12-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_metal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='style_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
