# Generated by Django 4.2.7 on 2025-12-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_productattribute_productimage_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['store', 'product'], name='stock_inven_store_i_ad7f0f_idx'),
        ),
    ]
