# Generated by Django 4.2.7 on 2025-12-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_user_is_email_verified_user_verification_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OldGoldTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('bill_of_supply_no', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('customer_pan', models.CharField(max_length=10)),
                ('customer_address', models.TextField(blank=True)),
                ('item_description', models.CharField(max_length=255)),
                ('gross_weight_before', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('purity_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gross_weight_after', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purity_after', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deduction_addition', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('net_weight_calculated', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gold_rate_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_gold_transactions', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_old_gold', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_gold_transactions', to='core.store')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
