# Generated by Django 4.2.7 on 2025-12-03 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(help_text='Position referred for', max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('interview', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='HR notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.company')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals_candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
