# Generated by Django 4.2.7 on 2025-12-03 01:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTLProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proposed_date', models.DateField()),
                ('location', models.CharField(help_text='Venue/Location for the activity', max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btl_proposals', to='core.company')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btl_to_approve', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btl_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'btl_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BTLImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='btl/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image_type', models.CharField(choices=[('plan', 'Plan/Setup'), ('execution', 'Execution'), ('result', 'Result/Outcome')], default='execution', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='btl.btlproposal')),
            ],
            options={
                'db_table': 'btl_images',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='btlproposal',
            index=models.Index(fields=['company', 'status'], name='btl_proposa_company_739a06_idx'),
        ),
        migrations.AddIndex(
            model_name='btlproposal',
            index=models.Index(fields=['user', '-created_at'], name='btl_proposa_user_id_41f271_idx'),
        ),
    ]
