# Generated by Django 4.2.7 on 2025-12-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_company_encryption_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(help_text='10-digit mobile number', max_length=10, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='affiliates', to='core.company')),
            ],
            options={
                'db_table': 'affiliates',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_name', models.CharField(max_length=255)),
                ('invitee_contact', models.CharField(max_length=10)),
                ('invitee_address', models.TextField(blank=True)),
                ('invitee_age', models.IntegerField(blank=True, null=True)),
                ('invitee_gender', models.CharField(blank=True, max_length=20)),
                ('interested_items', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='customer_referrals.affiliate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_referrals', to='core.company')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_referrals', to='core.store')),
            ],
            options={
                'db_table': 'customer_referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
